### ISSUE TITLE
Перевести верстку на bootstrap v4

### ISSUE THREAD

**Issue by WarmongeR1** [pythondigest/pythondigest#104]
сабж

**Comment by ivlevdenis** [comment]
Её сначала нужно почистить :smile:

**Comment by WarmongeR1** [comment]
@ivlevdenis а такие issue уже есть :) #88 #89 #90

**Comment by ivlevdenis** [comment]
Заметил локальные исправления по ui в некоторых pr, не нужно их делать. В #112 все уже исправлено, закинь его на поддомен что бы получить отчеты нравится/не нравится!

**Comment by timonefm** [comment]
кто нибудь взялся за верстку ?

**Comment by ivlevdenis** [comment]
@timonefm давно уже готово #112
