### ISSUE TITLE
Добавить документацию по локальному развертыванию pythondigest.

### ISSUE THREAD

**Issue by MrLokans** [pythondigest/pythondigest#106]
Необходимо создать информацию для разработчиков о том, как развернуть локально весь проект (что необходимо иметь в системе, как развернуть виртуальное окружение со всеми зависимостями, какие настройки добавить в приложение, мини-ФАК по командам)

**Comment by WarmongeR1** [comment]
+1.
Да, надо это сделать. 
В мае это сделаю, соберу набор фикстур, данных для запуска.

Спасибо

**Comment by WarmongeR1** [comment]
Добавил базовую информацию - https://github.com/pythondigest/pythondigest/blob/develop/README.md
Но еще добавлю фикстуры и потом начну писать FAQ по командам.
