### ISSUE TITLE
Изменить ordering новостей

### ISSUE THREAD

**Issue by iNerV** [pythondigest/pythondigest#114]
Если я правильно понимаю сейчас все новости в /feed идут в том порядке в каком они добавились на модерацию. а вот модерация/активация происходит в разнобой.

предлагаю поменять
[`items = items.order_by('-created_at', '-related_to_date')`](https://github.com/pythondigest/pythondigest/blob/master/digest/views.py#L129)
на
`items = items.order_by('-activated_at', '-related_to_date')`

вроде бы так будет правильно..

надоело, что иногда смотришь последние новости, а потом оказывается, что где-то в середине страницы вдруг появились новости которых ты не видел, потому что их активировали N минут назад.

**Comment by WarmongeR1** [comment]
Можешь сделать PR с этой правкой?
