### ISSUE TITLE
Отмечать видео в Atom

### ISSUE THREAD

**Issue by orgkhnargh** [pythondigest/pythondigest#70]
Не всегда есть время и достаточная полоса пропускания интернета для просмотра видео. Было бы удобно каким-либо образом предупреждать, что основным контентом конкретной новости является не текст, а видеозапись. Как вариант, можно указывать категорию с помощью [`atom:category`](http://tools.ietf.org/html/rfc4287#section-4.2.2). Также можно просто указывать на видео в тесте или заголовке. Например: `[Видео] Заголовок статьи`.

Спасибо.

**Comment by WarmongeR1** [comment]
Идея хорошая.

**Comment by WarmongeR1** [comment]
Закодил

**Comment by orgkhnargh** [comment]
Спасибо!
