### ISSUE TITLE
Не показывать медиа вставки на мобилках

### ISSUE THREAD

**Issue by alrusdi** [pythondigest/pythondigest#80]
На почту пришел баг репорт про то, что плывет верстка.
По-моему хорошо бы для узких экранов (телефоны в частности) вообще скрывать медиасодержимое. Не заморачиваясь, чисто с помощью CSS.
![image1](https://cloud.githubusercontent.com/assets/394311/14150755/fde36152-f6c3-11e5-8adf-31866900dd1e.PNG)

**Comment by WarmongeR1** [comment]
С помощью https://github.com/WarmongeR1/django-remdow внешняя статика подгружается на хост.
Тем же кодом расставляю класс `class="img-responsive"` из бутстрапа. 

Таким образом статика подгружается максимально быстро, а сам бутстрап подстраивает размеры.

**Comment by alrusdi** [comment]
Ну ладно тогда.
